---
services:
  jupyterlab:
    build:
      context: .
      dockerfile: docker/jupyterlab/Dockerfile
    image: jupyterlab:${IMAGE_TAG}
    command: start-notebook.sh --NotebookApp.token="" --NotebookApp.notebook_dir=/home/jovyan/work
    environment:
      - PYTHONPATH=/home/jovyan/
      - DATADIR=/home/jovyan/data
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work/nootbooks:rw
      - ./docstore:/home/jovyan/work/docstore:ro
      - ./data/jupyterlab:/home/jovyan/data:rw
      - $HOME/.openai:/home/.openai:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch